version: '3'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    volumes:
      - ./captured/server:/captured/server
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8081:8081"
