version: '3.8'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8080:8080
    networks:
      custom-network:
        ipv4_address: 192.168.1.3
    deploy:
      # https://docs.docker.com/compose/compose-file/deploy/#resources
      resources:
        limits:
          cpus: '0.50' # 0.50 (50% of a single core) of available processing time (CPU)
          memory: 1g # https://docs.docker.com/compose/compose-file/11-extension/#specifying-byte-values
    volumes:
      - ./captured/server:/captured/server

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 8081:8081
    networks:
      custom-network:
        ipv4_address: 192.168.1.2
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1gb

# https://docs.docker.com/compose/compose-file/06-networks/
networks:
  custom-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
